### ISSUE TITLE
Search export breaks if I export a search with a `count: ` filter

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph-search-export#4]
In the network request, it looks like we attach a count:999999 to the extension graphql search results request, which understandably breaks it if I already have a count (you can’t have two “count” filters).

We should handle this by only attaching the count:999999999 if a user doesn't pass a count.

**Comment by muratsu** [comment]
Blocked by: https://github.com/sourcegraph/sourcegraph/issues/19949
